env:
  _target_: 'hexarena.env.ForagingEnv'
  arena:
    resol: 2
  boxes:
    - num_patches: 9
    - num_patches: 9
    - num_patches: 9
model:
  p_s: # (pos, gaze, (food_1, cue_1), (food_2, cue_2), (food_3, cue_3))
    idcs: [[0], [1], [2, 3], [4, 5], [6, 7]]
