env:
  _target_: 'hexarena.env.ForagingEnv'
  arena:
    resol: 2
  boxes:
    - num_grades: 5
      num_patches: 1
    - num_grades: 5
      num_patches: 1
    - num_grades: 5
      num_patches: 1
  dt: 2.
model:
  p_s:
    idxs: [[0], [1], [2, 3], [4, 5], [6, 7]]
  p_o:
    idxs: [[0], [1], [2], [3], [4]]
