env:
  _target_: 'hexarena.env.ForagingEnv'
  arena:
    resol: 2
  boxes:
    - num_grades: 10
      num_patches: 1
    - num_grades: 10
      num_patches: 1
    - num_grades: 10
      num_patches: 1
  time_cost: 0.1
model:
  p_s: # (pos, gaze, (food_1, cue_1), (food_2, cue_2), (food_3, cue_3))
    idxs: [[0], [1], [2, 3], [4, 5], [6, 7]]
