apiVersion: batch/v1 # Jobs Default K8 API
kind: Job # This tells kubernetes what kind of class it is working with
metadata:
  name: marco-2k-notau # Name of the Job
spec:
  completions: 8
  parallelism: 8
  template: # Pod Templete
    metadata:
      labels:
        app: blender
    spec:
      restartPolicy: Never # Options are OnFailure, and Never.
      hostNetwork: true # This option will allow the pod to use the host network for internet access
      tolerations: # This toleration allows the pod to be schedule onto gpu-only pod machines, remove this if you are not using gpu
      - key: "gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 6G
      - name: data # name for the volume to be reference in container volumeMounts
        hostPath:
          path: /mnt/scratch09/zhe/hex-arena/data # Directory on the host machine to be mounted
      - name: store
        hostPath:
          path: /mnt/scratch09/zhe/hex-arena/store
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname # Target label is gpu_mem_size
                operator: NotIn # Key must have one of the following values
                values:
                - at-gencompute001
                - at-gencompute002
                - at-compute006 # calcium imaging
                - at-compute011
                - at-compute015 # light bead microscopy
                - poirot
                - at-mlflow
      containers: # Container Level
      - name: hex-arena # Container name
        image: zheli21/hexarena
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 8
            memory: 16G
          limits:
            cpu: 16
            memory: 32G
        volumeMounts: # Container reference to volumes define above
        - name: dshm
          mountPath: /dev/shm
        - name: data
          mountPath: /hex-arena/data
        - name: store
          mountPath: /hex-arena/store
        command: ["/bin/bash"] # Entry point for the container
        args:
          - "-c"
          - >
            python -u -m hexarena.scripts.poisson_beliefs
            subject=marco tau_in_state=False n_samples=2000
            max_wait=10 num_works=6 patience=3
