apiVersion: batch/v1 # Jobs Default K8 API
kind: Job # This tells kubernetes what kind of class it is working with
metadata:
  name: ppo-expo-001 # Name of the Job
spec:
  completions: 10
  parallelism: 5
  template: # Pod Templete
    spec:
      restartPolicy: Never # Options are OnFailure, and Never.
      hostNetwork: true # This option will allow the pod to use the host network for internet access
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 6G
      - name: data # name for the volume to be reference in container volumeMounts
        hostPath:
          path: /mnt/scratch09/zhe/hex-arena/data # Directory on the host machine to be mounted
      - name: store
        hostPath:
          path: /mnt/scratch09/zhe/hex-arena/store_May2025
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname # Target label is gpu_mem_size
                operator: NotIn # Key must have one of the following values
                values:
                - at-gencompute001
                - at-gencompute002
                - at-compute006 # calcium imaging
                - at-compute011
                - at-compute015 # light bead microscopy
                - at-mlflow
                - poirot
      containers: # Container Level
      - name: hex-arena # Container name
        image: zheli21/hexarena
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 4
            memory: 12G
          limits:
            cpu: 8
            memory: 24G
        volumeMounts: # Container reference to volumes define above
        - name: dshm
          mountPath: /dev/shm
        - name: data
          mountPath: /hex-arena/data
        - name: store
          mountPath: /hex-arena/store
        command: ["/bin/bash"] # Entry point for the container
        args:
          - "-c"
          - >
            python -u -m hexarena.scripts.train_agents
            kappa=0.01 schedule=Expo
            num_epochs=10 num_works=10 max_wait=10
