box:
  PoissonBox:
    _init_:
      max_tau: 36. # sec

env:
  ForagingEnv:
    _init_:
      arena:
        _target_: hexarena.arena.Arena
      monkey:
        _target_: hexarena.monkey.Monkey
      box:
        _target_: hexarena.box.PoissonBox
  SimilarBoxForagingEnv:
    _init_:
      box:
        _target_: hexarena.box.StationaryBox
