arena:
  Arena:
    _init_:
      resol: 2

monkey:
  Monkey:
    _init_:
      push_cost: 1.
      turn_price: 0.001 # deg^{-1}
      move_price: 0.
      look_price: 0.001 # deg^{-1}

box:
  BaseFoodBox:
    _init_:
      dt: 1.0 # sec
      reward: 10.
      num_levels: 3
      num_grades: 8
      num_patches: 1
      sigma: 0.05
  PoissonBox:
    _init_:
      tau: 20 # sec
  VolatileBox:
    _init_:
      volatility: 0.05 # 1/sec

env:
  ForagingEnv:
    _init_:
      time_cost: 0.
      dt: 1.0 # sec
      arena:
        _target_: hexarena.arena.Arena
      monkey:
        _target_: hexarena.monkey.Monkey
      box:
        _target_: hexarena.box.PoissonBox
